### PR TITLE
Ray recipe

### PR DESCRIPTION
**Pull request by npanpaliya**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
Great! Thanks @npanpaliya !
Does Ray work with Py37 as well. I only see 3.6 in this PR.

**Comment by npanpaliya** [comment]
> Great! Thanks @npanpaliya !
> Does Ray work with Py37 as well? I only see 3.6 in this PR.

Yes, it does. I've added the configuration for py3.7. But unfortunately the builds are not working with some weird download errors for pre-reqs packages. I've tried `conda clean -f` or `conda clean --all` but no luck.

**Comment by npanpaliya** [comment]
I'll create a new PR with just one commit for adding ray recipe. This PR shows 87 commits to be merged as I think web editor was used earlier to modify files.

**Comment by jayfurmanek** [comment]
Published in https://github.com/IBM/powerai/pull/212

**Pull request closed without merging**
