### PR TITLE
TensorFlow Serving Examples

### PR DESCRIPTION
**Pull request by wdirons**
In preparation for a blog on TensorFlow Serving, move the example
code to an external github repo.

movie_reviews_training.py - trains the model to be served.
rest_client.py - Example REST client interface request.
grpc_client.py - Example gPRC client interface request.
batch_rest_client_example.py - Example batch interface request.

### CODE REVIEW

**Comment by wdirons** [comment]
@jayfurmanek , can you review/approve? And does @dllehr81 do the merge?

**Comment by wdirons** [comment]
movie_reviews_training.py was based off of: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/keras/basic_text_classification.ipynb

I converted it into a python program with arg parsing and a main. And I named the input and output layers and added a line to save the model.

**Comment by jayfurmanek** [comment]
OK. Since you made changes, add an additional IBM header as well, similar to the others.

**Comment by wdirons** [comment]
I add the IBM copyright to movie_reviews_training.py

**Pull request merged**
