### PR TITLE
h5py recipe

### PR DESCRIPTION
**Pull request by wdirons**
Based on https://github.com/AnacondaRecipes/h5py-feedstock
Only for ppc64le, as 2.9.0 is available from Anaconda for x86_64

### CODE REVIEW

**Comment by ipoddar-ibm** [comment]
can this PR be submitted to conda-forge?

**Comment by wdirons** [comment]
> can this PR be submitted to conda-forge?

conda-forge always has a h5py package and a PR for ppc64le support: https://github.com/conda-forge/h5py-feedstock/pull/62

The conda-forge package is more complex as it includes different types of mpi support. I looked at the PR for ppc64le, but I didn't understand why the builds were failing.

**Comment by jayfurmanek** [comment]
I agree that it would be good to fix the conda-forge version, but I've not been able to figure out the issue there either. The added MPI features make it a bit of a different beast.

**Comment by ax3l** [comment]
got the upstream PR for ppc64le ready now, will land soon on conda-forge.

**Comment by ax3l** [comment]
Just saw you linking this:
ppc64le (and aarch64) support has now landed in conda-forge for h5py: https://github.com/conda-forge/h5py-feedstock/pull/62

**Comment by jayfurmanek** [comment]
That's great! Thanks!

**Pull request merged**
