### PR TITLE
Unifying Travis recipes

### PR DESCRIPTION
**Pull request by lcnzg**
Hi. I unified the pygdf and cupy recipes into one that can be run in Travis. You will need to enable the Travis CI running to this repository, and may even enable the Travis "Cron Jobs" to run the builds and upload to ftp periodically.

Note: The Travis matrix env can't be used with stages, so I needed to create manually each job and repeat the code.

There is the result in my fork:
powerai-travis

Please contact me if there are any problems.

### CODE REVIEW

**Comment by ipoddar-ibm** [comment]
We will have (hopefully) more recipes in the future. Do you expect all of them to fit into one recipe? Also any idea why the build is failing?

**Comment by lcnzg** [comment]
Travis does not currently support multiple travis.yml running together. (https://github.com/travis-ci/travis-ci/issues/3540) The only ways this happens is to create a recipe that runs all softwares or have a different recipe per branch for each software.

The build is failing because Travis-ci.com is using Architecture: x86_64 (line 573) while Travis-ci.org is using Architecture: ppc64le (line 460 in https://travis-ci.org/lcnzg/powerai/jobs/449149007).

**Comment by sivakkri** [comment]
@lcnzg Is there any reason why the builds are happening in travis-ci.com instead of travis-ci.org ?.  Are you explicitly kick starting the builds on travis-ci.com ?.   As you mentioned, since the above recipes need a ppc64le docker image (nvidia/cuda-ppc64le:9.2-cudnn7-devel-ubuntu16.04),  they will fail with "exec format error" if run on a x86 based VM.

**Comment by lcnzg** [comment]
@sivakkri I don't have permission to configure any CI into this repository. I think that travis-ci.com build started automatically due to some previous configuration of the IBM repositories. You will need to disable travis-ci.com and enable travis-ci.org for this repo.

**Comment by ipoddar-ibm** [comment]
@lcnzg sorry for the long delay, we were discussing whether this is the right repo for these recipes. The conclusion is that for now it is until we figure out a better repo structure. Also I made some changes to travis-ci.com to disable building this repo and enabled automated builds from travis-ci.org. Let me merge and then initiate a new build from travis-ci.org on ppc64le. if there are any failures, I will bring that to your attention.

**Comment by ipoddar-ibm** [comment]
Build: https://travis-ci.org/IBM/powerai/builds/460949019

**Comment by amdabhad** [comment]
When I fork and clone this git repo and create a PR, the build fails with following error:
mirror: Login failed: 530 Anonymous sessions must use encryption.

You can see build output here: https://travis-ci.org/amdabhad/powerai/jobs/463158899#L3834

**Comment by lcnzg** [comment]
@amdabhad Yes, because the ftp username and password are available only to the original repository, for security reasons. When running on forks, you need to remove the upload command.

**Comment by ipoddar-ibm** [comment]
@lcnzg can we introduce a default mode .travis.yml which does not upload the built packages? I want all PRs to show successful builds.

**Comment by lcnzg** [comment]
@ipoddar-ibm The pull requests in this repository will show successful because of the statement "if [ "$TRAVIS_PULL_REQUEST" = "false" ];". But on forks, commits will execute the upload command and fail.
Maybe, if we create a new variable in Travis Menu, and use this to define another if statement, we can check if the repository is the original to execute the upload command. And prevent this command from running on forks.

**Comment by amdabhad** [comment]
@lcnzg Also I see all the recipes are built for every build which is takes more time. Is there any way, we can build only newly added recipes?

**Comment by amdabhad** [comment]
@lcnzg @ipoddar-ibm I see we have started using x86 system recently for building these recipes and earlier we were using a ppc system. But aren't we supposed to build these on ppc?

**Comment by lcnzg** [comment]
> @lcnzg Also I see all the recipes are built for every build which takes more time. Is there any way, we can build only newly added recipes?

@amdabhad Only if we create different branches for each individual recipe. With the current structure of the repo, this is not possible.

**Comment by ipoddar-ibm** [comment]
@lcnzg will you be updating the repodata.json file in this channel: https://oplab9.parqtec.unicamp.br/pub/ppc64el/power-ai/linux-ppc64le/repodata.json to include the newly added packages cupy, pygdf and openjdk?

**Comment by jayfurmanek** [comment]
I think the best option for these recipes (eventually) is conda-forge. 

I got ppc64le into the anvil image:
https://github.com/conda-forge/docker-images/tree/master/linux-anvil2

And we had two attempts on the conda-smithy changes:
https://github.com/conda-forge/conda-smithy/pull/763
https://github.com/conda-forge/conda-smithy/pull/882

But didn't quite make it to the finish line there.

Will all of this work getting Travis to work right from this little repo, maybe we could focus on conda-forge, which can work with Travis, and benefit from a much larger pay off.

thoughts?

**Comment by jayfurmanek** [comment]
@ipoddar-ibm Sure thing!
If anyone gets a chance, the conda-smithy PR likely needs an update as there are merge conflicts now.

**Comment by lcnzg** [comment]
> @lcnzg will you be updating the repodata.json file in this channel: https://oplab9.parqtec.unicamp.br/pub/ppc64el/power-ai/linux-ppc64le/repodata.json to include the newly added packages cupy, pygdf and openjdk?

I will look at it, but I think the best way to have this file updated is to include its generation inside the Travis recipe. For now, if you have the new file with you, I can update it manually.
Also, at the moment, Travis has a bug that runs everything in x86. Because of that, our ppc64le recipes fail, but I hope it will be fixed soon.

**Pull request merged**
